### ISSUE TITLE
Issue in Woocommerce version 3.8.1 / Wordpress version 5.3.2

### ISSUE THREAD

**Issue by isasouza01** [valdeirs2/woocommerce-shipping-calculator-in-product#14]
Hello! I'm having the following issues in Woocommerce version 3.8.1 / Wordpress version 5.3.2

My debug file:

`[07-Jan-2020 17:42:44 UTC] id was called incorrectly. As propriedades do produto não devem ser acessadas diretamente. Backtrace: do_action('wp_ajax_nopriv_wscp_ajax_postcode'), WP_Hook->do_action, WP_Hook->apply_filters, Correios_Shipping_Ajax_Postcode->wscp_ajax_postcode, Correios_Shipping_Ajax_Postcode->get_product_shipping_estimate, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[07-Jan-2020 17:42:44 UTC] The WC_Product::get_price_excluding_tax function is deprecated since version 3.0. Replace with wc_get_price_excluding_tax.
[07-Jan-2020 17:42:44 UTC] The WC_Product::get_price_including_tax function is deprecated since version 3.0. Replace with wc_get_price_including_tax.
[07-Jan-2020 17:42:44 UTC] id was called incorrectly. As propriedades do produto não devem ser acessadas diretamente. Backtrace: do_action('wp_ajax_nopriv_wscp_ajax_postcode'), WP_Hook->do_action, WP_Hook->apply_filters, Correios_Shipping_Ajax_Postcode->wscp_ajax_postcode, Correios_Shipping_Ajax_Postcode->get_product_shipping_estimate, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.`

How can we solve it?

Thanks a lot!

**Comment by zaninijunior** [comment]
Estou com o mesmo problema.

Thu May 21 23:30:41.619362 2020] [proxy_fcgi:error] [pid 30511] [client 191.181.57.226:60514] AH01071: Got error 'PHP message: id was called incorrectly. As propriedades do produto n\xc3\xa3o devem ser acessadas diretamente. Backtrace: do_action('wp_ajax_nopriv_wscp_ajax_postcode'), WP_Hook->do_action, WP_Hook->apply_filters, Correios_Shipping_Ajax_Postcode->wscp_ajax_postcode, Correios_Shipping_Ajax_Postcode->get_product_shipping_estimate, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.PHP message: The WC_Product::get_price_excluding_tax function is deprecated since version 3.0. Replace with wc_get_price_excluding_tax.PHP message: The WC_Product::get_price_including_tax function is deprecated since version 3.0. Replace with wc_get_price_including_tax.PHP message: id was called incorrectly. As propriedades do produto n\xc3\xa3o devem ser acessadas diretamente. Backtrace: do_action('wp_ajax_nopriv_wscp_ajax_postcode'), WP_Hook->do_action, WP_Hook->apply_filters, Correios_Shipping_Ajax_Postcode->wscp_ajax_postcode, Correios_Shipping_Ajax_Postcode->get_product_shipping_estimate, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.'

**Comment by damianCARVALHO** [comment]
tbm estou... conseguiram resposta?

**Comment by valdeirs2** [comment]
Obrigado pelo report.
Resolvido no [7970651](https://github.com/valdeirs2/woocommerce-shipping-calculator-in-product/commit/7970651e012efb3677074b01940984075f4c52cd)
